version: '3.8'
services:
  nismoau_net_tools:
    restart: unless-stopped
    image: "<server:port>/docker/nismoau/nismoau_net_tools:latest"
    networks:
      - host
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: '100M'
        limits:
          cpus: '0.4'
          memory: '200M'

networks:
  host:
    name: host
    external: true